apiVersion: v1
kind: ConfigMap
metadata:
    name: node-label-operator 
    namespace: node-label-operator-system 
data:
    labelPrefix: "azure.tags"
    tagPrefix: ""
    conflictPolicy: "arm-precedence"
    syncDirection: "arm-to-node"
    minSyncPeriod: "1m"
