name: E2E
on:
  schedule:
  - cron: '0 0 * * *'
  pull_request:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build Controller
      run: make
      
    - name: AKS-Engine E2E Tests
      env:
        KUBECONFIG_OUT={{ secrets.AKSE_KUBECONFIG }}
      run: make e2e-test
      
    - name: AKS E2E Tests
      env:
        KUBECONFIG_OUT={{ secrets.AKS_KUBECONFIG }}
      run: make e2e-test
